#!/bin/bash

if [ ! -d "venv" ]; then
    echo "Installing requirements..."
    python3 -m venv venv
    source venv/bin/activate
    pip install -r requirements.txt
else
    source venv/bin/activate
fi

# Run the main application
python main.py
